machine:
  environment:
    PATH: $HOME/miniconda/bin:$PATH
    PYTHONHASHSEED: 0
    OMP_NUM_THREADS: 1
    PYEMMA_NJOBS: 1

dependencies:
  cache_directories:
    - $HOME/miniconda/

checkout:
  post:
    - git fetch --unshallow || true

dependencies:
  override:
    - devtools/ci/circle/install_miniconda.sh
    - conda config --add channels conda-forge
    - conda config --set always_yes true
    - conda env create -f environment.yml
    - conda install -n pyemma_tutorial nbval
test:
  override:
    - pytest --nbval -v notebooks/ 
