version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 1
      PYEMMA_NJOBS: 1
    parallelism: 4
    steps:
      - checkout
      - run:
          name: conda_config
          command: |
            conda config --add channels conda-forge
            conda config --set always_yes true
            conda config --set quiet true
      - run: conda install conda-build
      - run: conda build .
      - store_test_results:
          path: ~/junit

