version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHONHASHSEED: 0
      OMP_NUM_THREADS: 1
      PYEMMA_NJOBS: 1
      NBVAL_OUTPUT: /root/nbval
    parallelism: 4
    steps:
      - checkout
      - run:
          name: conda_config
          command: |
            conda config --set always_yes true
            conda config --set quiet true
      - run: conda install conda-build
      - run: mkdir $NBVAL_OUTPUT
      - run:
          name: build_test
          command: conda build -c conda-forge .
          no_output_timeout: 20m
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: /root/nbval #$NBVAL_OUTPUT
