package:
  name: pyemma_tutorials
  version: dev

source:
   - path: ../..

build:
  script: python -m pip install --no-deps --ignore-installed . -v
  entry_points:
    - pyemma_tutorials = pyemma_tutorials.cli:main

  osx_is_app: True
  noarch: python


requirements:
  build:
    - pip
  run:
    - pyemma
    - mdshare
    - notebook
    - nglview
    - jupyter_contrib_nbextensions
    - nbexamples

test:
  imports:
    - pyemma_tutorials
  commands:
    - which pyemma_tutorials  # [osx or linux]
  source_files:
    - conftest.py
  requires:
    - nbval

  commands: mkdir ~/junit || py.test --nbval -v --junit-xml=$HOME/junit/test.xml --pyargs pyemma_tutorials
