package:
  name: pyemma_tutorials
  version: dev

source:
   - path: ../..
   - path: ./

build:
  requirements:
    - pip
  #script: ls ; pip install . ; ls {{ PREFIX }}
  script: python setup.py install

  entry_points:
    - pyemma_tutorial = pyemma_tutorials:main

  osx_is_app: True
  noarch: python
  always_include_files:
    - pyemma_tutorial_notebooks/*


#requirements:
  # TODO: pin version
  #run:
  #  - pyemma
  #  - mdshare
   # - notebook
   # - nglview
   # - jupyter_contrib_nbextensions


test:
  #requires:
  #  - nbval

  commands: pwd; where py.test; py.test --nbval -v --junit-xml=$HOME/junit/test.xml {{ PREFIX + '/pyemma_tutorial_notebooks'}}
  #`python -c "import pyemma_tutorials as p; print(p.notebook_location)"`
